### ISSUE TITLE
File size limits?

### ISSUE THREAD

**Issue by MagisDing** [clydeclements/AsciiDocQuickLook#1]
Hi, the plugin works for my .adoc files which size is less than 10kb, but it could not manage to get the preview of .adoc larger than 10kb. 

Here is one of the files that couldn't be previewed by QuickLook.

https://cl.ly/5b4eb2736eed

**Comment by clydeclements** [comment]
I can confirm that no preview is generated for me either with the file you provided. Thanks for reporting this.

As a test, I converted the AsciiDoc file to HTML using `asciidoctor` directly, which is what the Quick Look plug-in does behind the scenes. That process was speedy, taking less than a second on my Mac. I could then preview the HTML file using Quick Look without issue. It seems like the plug-in *should* be able to handle a file of this size and/or complexity, and so the problem may be deeper. I will dig into my code to see what's happening with this file.

**Comment by clydeclements** [comment]
I had a flaw in how I was reading the generated HTML content from the `asciidoctor` process. I was waiting for the conversion process to finish before reading data from the pipe, which had a buffer of size 64KB. Thus if the associated HTML content for an AsciiDoc file was larger than the buffer size, the end result was that the preview generation never finished.

So there was indeed a file size limit, but that is fixed now in the latest release.
